// packages/ngx-guides/src/app/app.component.ts
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { NgxGuidesComponent } from 'projects/ngx-guides/src/public-api';
import Dragger from '@daybrush/drag';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  title = 'ngx-guides-app';
  @ViewChild('guides1', { static: false }) guides1: NgxGuidesComponent;
  @ViewChild('guides2', { static: false }) guides2: NgxGuidesComponent;
  private dragger: Dragger;
  private scrollX = 0;
  private scrollY = 0;
  ngAfterViewInit() {
    window.addEventListener('resize', this.onResize);

    this.dragger = new Dragger(document.body, {
      drag: e => {
        this.scrollX -= e.deltaX;
        this.scrollY -= e.deltaY;

        this.guides1.scroll(this.scrollX);
        this.guides1.scrollGuides(this.scrollY);
        this.guides2.scroll(this.scrollY);
        this.guides2.scrollGuides(this.scrollX);
      },
    });

    this.onResize();
  }
  onResize = () => {
    this.guides1.resize();
    this.guides2.resize();
  }
  onRestore = () => {
    this.scrollX = 0;
    this.scrollY = 0;
    this.guides1.scroll(0);
    this.guides1.scrollGuides(0);
    this.guides2.scroll(0);
    this.guides2.scrollGuides(0);

  }
}

<div class="box" #boxRef (click)="onRestore()"></div>
<div class="ruler horizontal">
  <ngx-guides #guides1 type="horizontal" [rulerStyle]='{ left: "30px", width: "calc(100% - 30px)", height: "30px"}'></ngx-guides>
</div>
<div class="ruler vertical">
  <ngx-guides #guides2 type="vertical"  [rulerStyle]='{ top: "30px", height: "calc(100% - 30px)", width: "30px"}'></ngx-guides>
</div>

<div class="container">
  <img
    src="https://daybrush.com/guides/images/guides.png"
    width="200"
    alt="guides" />
  <p class="dragit">Drag Screen & Rulers!</p>
  <p class="badges">
    <a href="https://www.npmjs.com/package/svelte-guides" target="_blank">
      <img
        src="https://img.shields.io/npm/v/svelte-guides.svg?style=flat-square&color=007acc&label=version"
        alt="npm version" />
    </a>
    <a href="https://github.com/daybrush/guides" target="_blank">
      <img
        src="https://img.shields.io/github/stars/daybrush/guides.svg?color=42b883&style=flat-square" />
    </a>
    <a href="https://github.com/daybrush/guides" target="_blank">
      <img
        src="https://img.shields.io/badge/language-typescript-blue.svg?style=flat-square" />
    </a>
    <a
      href="https://github.com/daybrush/guides/blob/master/LICENSE"
      target="_blank">
      <img
        src="https://img.shields.io/github/license/daybrush/guides.svg?style=flat-square&label=license&color=08CE5D" />
    </a>
    <a
      href="https://github.com/daybrush/guides/tree/master/packages/react-guides"
      target="_blank">
      <img
        alt="React"
        src="https://img.shields.io/static/v1.svg?label=&message=React&style=flat-square&color=61daeb" />
    </a>
    <a
      href="https://github.com/daybrush/guides/tree/master/packages/preact-guides"
      target="_blank">
      <img
        alt="Preact"
        src="https://img.shields.io/static/v1.svg?label=&message=Preact&style=flat-square&color=673ab8" />
    </a>
    <a
      href="https://github.com/daybrush/guides/tree/master/packages/ngx-guides"
      target="_blank">
      <img
        alt="Angular"
        src="https://img.shields.io/static/v1.svg?label=&message=Angular&style=flat-square&color=C82B38" />
    </a>
    <a
      href="https://github.com/daybrush/guides/tree/master/packages/vue-guides"
      target="_blank">
      <img
        alt="Vue"
        src="https://img.shields.io/static/v1.svg?label=&message=Vue&style=flat-square&color=3fb984" />
    </a>
    <a
      href="https://github.com/daybrush/guides/tree/master/packages/svelte-guides"
      target="_blank">
      <img
        alt="Svelte"
        src="https://img.shields.io/static/v1.svg?label=&message=Svelte&style=flat-square&color=C82B38" />
    </a>
  </p>
  <p class="description">
    A Svelte Guides component that can draw ruler and manage guidelines.
  </p>
  <div class="buttons">
    <a
      href="https://github.com/daybrush/guides/tree/master/packages/svelte-guides"
      target="_blank">
      Download
    </a>
    <!-- <a href="./release/latest/doc" target="_blank">API</a> -->
  </div>
</div>

// packages/react-guides/src/demo/App.tsx
import { Component } from "react";
import * as React from "react";
import Scene from "scenejs";
import "./App.css";
import Guides from "../react-guides/Guides";
import { ref } from "framework-utils";
import Dragger from "@daybrush/drag";

export default class App extends Component<{}> {
    private scene: Scene = new Scene();
    // private editor!: Editor;
    private guides1: Guides;
    private guides2: Guides;
    private scrollX: number = 0;
    private scrollY: number = 0;
    public render() {
        return (<div className="page">
            <div className="box" onClick={this.restore}></div>
            <div className="ruler horizontal">
                <Guides ref={ref(this, "guides1")}
                    type="horizontal"
                    rulerStyle={{ left: "30px", width: "calc(100% - 30px)", height: "100%" }}
                    setGuides={(guides) => {
                        console.log("horizontal", guides);
                    }}
                />
            </div>
            <div className="ruler vertical">
                <Guides ref={ref(this, "guides2")}
                    type="vertical"
                    rulerStyle={{ top: "30px", height: "calc(100% - 30px)", width: "100%" }}
                    setGuides={(guides) => {
                        console.log("vertical", guides);
                    }}
                />
            </div>
            <div className="container">
                <img src="https://daybrush.com/guides/images/guides.png" width="200" alt="guides" />
                <p className="dragit">Drag Screen & Rulers!</p>
                <p className="badges">
                    <a href="https://www.npmjs.com/package/svelte-guides" target="_blank">
                        <img src="https://img.shields.io/npm/v/svelte-guides.svg?style=flat-square&color=007acc&label=version"
                            alt="npm version" /></a>
                    <a href="https://github.com/daybrush/guides" target="_blank">
                        <img src="https://img.shields.io/github/stars/daybrush/guides.svg?color=42b883&style=flat-square" /></a>
                    <a href="https://github.com/daybrush/guides" target="_blank">
                        <img src="https://img.shields.io/badge/language-typescript-blue.svg?style=flat-square" />
                    </a>
                    <a href="https://github.com/daybrush/guides/blob/master/LICENSE" target="_blank">
                        <img
                            src="https://img.shields.io/github/license/daybrush/guides.svg?style=flat-square&label=license&color=08CE5D" />
                    </a>
                    <a href="https://github.com/daybrush/guides/tree/master/packages/react-guides" target="_blank"><img alt="React"
                        src="https://img.shields.io/static/v1.svg?label=&message=React&style=flat-square&color=61daeb" /></a>
                    <a href="https://github.com/daybrush/guides/tree/master/packages/preact-guides" target="_blank"><img alt="Preact"
                        src="https://img.shields.io/static/v1.svg?label=&message=Preact&style=flat-square&color=673ab8" /></a>
                    <a href="https://github.com/daybrush/guides/tree/master/packages/ngx-guides" target="_blank"><img alt="Angular"
                        src="https://img.shields.io/static/v1.svg?label=&message=Angular&style=flat-square&color=C82B38" /></a>
                    <a href="https://github.com/daybrush/guides/tree/master/packages/vue-guides" target="_blank"><img alt="Vue"
                        src="https://img.shields.io/static/v1.svg?label=&message=Vue&style=flat-square&color=3fb984" /></a>
                    <a href="https://github.com/daybrush/guides/tree/master/packages/svelte-guides" target="_blank"><img alt="Svelte"
                        src="https://img.shields.io/static/v1.svg?label=&message=Svelte&style=flat-square&color=C82B38" /></a>
                </p>
                <p className="description">A React Guides component that can draw ruler and manage guidelines.</p>
                <div className="buttons">
                    <a href="https://github.com/daybrush/guides/tree/master/packages/svelte-guides" target="_blank">Download</a>
                </div>
            </div>
        </div>
        );
    }
    public componentDidMount() {
        new Dragger(document.body, {
            drag: e => {
                this.scrollX -= e.deltaX;
                this.scrollY -= e.deltaY;

                this.guides1.scrollGuides(this.scrollY);
                this.guides1.scroll(this.scrollX);

                this.guides2.scrollGuides(this.scrollX);
                this.guides2.scroll(this.scrollY);
            },
        });
        window.addEventListener("resize", () => {
            this.guides1.resize();
            this.guides2.resize();
        });
    }
    public restore = () => {
        this.scrollX = 0;
        this.scrollY = 0;
        this.guides1.scroll(0);
        this.guides1.scrollGuides(0);
        this.guides2.scroll(0);
        this.guides2.scrollGuides(0);
    }
}
