// packages/svelte-guides/src/Guides.svelte
<script lang="ts">
  import VanillaGuides, {
    GuidesOptions,
    PROPERTIES
  } from "@scena/guides";

  import {
    onMount,
    onDestroy,
    beforeUpdate,
    afterUpdate,
    tick
  } from "svelte";

  export let style = { width: "100%", height: "100%"};

  declare var $$props: any;
  let options: Partial<GuidesOptions> = {};
  let guides: VanillaGuides;
  let guidesElement: HTMLElement;

  function setStyle() {
    const el = options.container || guidesElement;
    const elStyle = el.style;

    for (const name in style) {
      if (elStyle[name] === style[name]) {
        continue;
      }
      elStyle[name] = style[name];
    }
  }
  beforeUpdate(() => {
    const props = $$props;

    options = {};
    PROPERTIES.forEach(name => {
      if (name === "style") {
        return;
      }
      if (name in props) {
        (options as any)[name] = props[name];
      }
    });
    if (guides) {
      guides.setState(options);
      setStyle();
    }
  });
  onMount(() => {
    setStyle();
    guides = new VanillaGuides(options.container || guidesElement, options);
  });
  onDestroy(() => {
    guides.destroy();
  });

  export function resize() {
    guides.resize();
  }
  export function scroll(scrollPos: number) {
    guides.scroll(scrollPos);
  }
  export function scrollGuides(scrollPos: number) {
    guides.scrollGuides(scrollPos);
  }
  export function getGuides() {
    return guides.getGuides();
  }
</script>
{#if !options.container}
<div class="guides" bind:this={guidesElement} />
{/if}

// src/Guides.tsx
import { ref, Properties } from "framework-utils";
import { h, render } from "preact";
import { PROPERTIES } from "./consts";
import { GuidesInterface } from "@scena/react-guides/declaration/types";
import InnerGuides from "./InnerGuides";
import { GuidesOptions } from "./types";

@Properties(PROPERTIES, (prototype, property) => {
    Object.defineProperty(prototype, property, {
        get() {
            return this.getPreactGuides().props[property];
        },
        set(value) {
            this.innerGuides.setState({
                [property]: value,
            });
        },
        enumerable: true,
        configurable: true,
    });
})
class Guides implements GuidesInterface {
    private tempElement = document.createElement("div");
    private innerGuides!: InnerGuides;

    constructor(container: HTMLElement, options: Partial<GuidesOptions> = {}) {
        render(
            <InnerGuides ref={ref(this, "innerGuides")}
                {...options} container={container} />,
            this.tempElement,
        );
    }
    public scroll(scrollPos: number) {
        this.getPreactGuides().scroll(scrollPos);
    }
    public scrollGuides(scrollPos: number) {
        this.getPreactGuides().scrollGuides(scrollPos);
    }
    public resize() {
        this.getPreactGuides().resize();
    }
    public getGuides() {
        return this.getPreactGuides().getGuides();
    }
    public setState(state: any, callback?: () => void) {
        this.innerGuides.setState(state, callback);
    }
    public destroy() {
        render("", this.tempElement);
        this.tempElement = null;
        this.innerGuides = null;
    }
    private getPreactGuides() {
        return this.innerGuides.preactGuides;
    }
}

export default Guides;
